---
# Deploy OSUSEC WiFi demo

- name: apply common config
  hosts: all
  roles:
    - common

- name: apply webserver config
  hosts: webserver
  roles:
     - webserver

- name: apply mitm config
  hosts: mitm
  roles:
     - mitm

#- name: apply vpnserver config
#  hosts: vpnserver
#  roles:
#    - vpnserver
#
#- name: build attacker system
#  hosts: attacker
#  roles:
#    - attacker
#
#- name: build victim system
#  hosts: victim
#  roles:
#    - victim