---
# Deploy demo site

- name: Copy over source code
  copy:
    src: mitm_code/
    dest: "/var/www/{{ mitm_dns }}/"

- name: Configure vhost
  template:
    src: vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ mitm_dns }}.conf"

- name: Enable vhost
  command: a2ensite {{ mitm_dns }}
  args:
    creates: "/etc/apache2/sites-enabled/{{ mitm_dns }}.conf"
  notify:
    - restart apache